repository: ferjgar/ferjgar.github.io
# crazy XD https://github.com/github/pages-gem/issues/399
github: [metadata]

permalink: /:title

paginate: 2
paginate_path: /pag/:num

timezone: Europe/Madrid

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
