exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

paginate: 2
paginate_path: /pag/:num

permalink: /:title

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

repository: ferjgar/ferjgar.github.io

sass:
  sass_dir: _sass
  style: :compressed

timezone: Europe/Madrid
