permalink:         /:title

paginate:          2
paginate_path:     /pag/:num

timezone:          Europe/Madrid

sass:
  sass_dir:        _sass
  style:           :compressed

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
